
spring:
  application:
    name: yanhuo-platform
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB


server:
  port: 8803
  servlet:
    context-path: /platform



### 调度中心部署根地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
yanhuo:
  admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
  ### 执行器通讯TOKEN [选填]：非空时启用；
  accessToken: default_token
  executor:
     appname: yanhuo-xxl-job-executor
     ip: 127.0.0.1
     port: 9998
     logpath: ./data/applogs/xxl-job/jobhandler
     logretentiondays: 30

oss:
  type: 1 #0是本地存储，1是七牛云存储